/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kwhat_jnativehook_GlobalScreen */

#ifndef _Included_com_github_kwhat_jnativehook_GlobalScreen
#define _Included_com_github_kwhat_jnativehook_GlobalScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getNativeMonitors
 * Signature: ()[Lcom/github/kwhat/jnativehook/NativeMonitorInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getNativeMonitors
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getAutoRepeatRate
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getAutoRepeatRate
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getAutoRepeatDelay
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getAutoRepeatDelay
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getPointerAccelerationMultiplier
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getPointerAccelerationMultiplier
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getPointerAccelerationThreshold
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getPointerAccelerationThreshold
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getPointerSensitivity
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getPointerSensitivity
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    getMultiClickIterval
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_getMultiClickIterval
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kwhat_jnativehook_GlobalScreen
 * Method:    postNativeEvent
 * Signature: (Lcom/github/kwhat/jnativehook/NativeInputEvent;)V
 */
JNIEXPORT void JNICALL Java_com_github_kwhat_jnativehook_GlobalScreen_postNativeEvent
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
